In [3]:
import numpy as np

data = [0.052,0.967,-0.074,0.238,9.694,152.635,3.752]
# data = [-0.032,-0.682,-0.029,0.730,355.046,273.956,0.066]
# data = [0.015,-0.274,0.017,0.961,2.216,328.194,1.401]
# data = [-0.008,0.853,0.025,0.522,357.027,117.046,0.726]
# data = [0.115,0.026,-0.138,0.983,13.441,1.094,344.156]
# data = [0.034,0.979,-0.181,0.083,21.124,170.745,2.283]
# data = [0.013,0.976,-0.170,0.132,19.643,164.360,358.803]

q1 = data[:4]
q2 = [q1[3], q1[0], q1[1], q1[2]]

euler = data[4:]
euler_x, euler_y, euler_z = euler

def quat_to_rotmat(quat):
    qx, qy, qz, qw = quat

    rot_mat = np.array([
    [1-2*qy**2-2*qz**2, 2*qx*qy-2*qz*qw, 2*qx*qz+2*qy*qw],
    [2*qx*qy+2*qz*qw, 1-2*qx**2-2*qz**2, 2*qy*qz-2*qx*qw],
    [2*qx*qz-2*qy*qw, 2*qy*qz+2*qx*qw, 1-2*qx**2-2*qy**2]
    ])

    return rot_mat

r1 = quat_to_rotmat(q1)
print(r1)


from pyquaternion import Quaternion
Q2 = Quaternion(q2)
r2 = Q2.rotation_matrix
print(r2)

print('r1-r2', np.abs(r1-r2).sum())

print('\nEuler')
print(euler)

z, y, x = Q2.euler_angles("YXZ")
print(np.degrees([x, y, z])%360)

[[-0.88113   0.135792  0.452596]
 [ 0.065344  0.98364  -0.167868]
 [-0.467988 -0.118364 -0.875586]]
[[-0.88129367  0.13580381  0.45263538]
 [ 0.06534969  0.98363858 -0.16788261]
 [-0.46802872 -0.1183743  -0.87574919]]
r1-r2 0.0004507886546136347

Euler
[9.694, 152.635, 3.752]


AttributeError: 'Quaternion' object has no attribute 'euler_angles'